name: Build Datavyu

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]

    env:
      MAVEN_FLAGS: "-B -ntp"
      MAVEN_OPTS: >-
        -Xmx2g
        -Dfile.encoding=UTF-8
        -Dswing.aatext=true
        -Dawt.useSystemAAFontSettings=lcd
        -Dorg.apache.maven.wagon.httpconnectionManager.ttl=120000
        -Dorg.apache.maven.wagon.http.retryHandler.count=2

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '8'
          cache: 'maven'

      - name: Set up Maven mirrors (Aliyun)
        run: |
          mkdir -p "$HOME/.m2"
          cat > "$HOME/.m2/settings.xml" <<'XML'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <mirrors>
              <mirror>
                <id>aliyun-all</id>
                <mirrorOf>*</mirrorOf>
                <name>Aliyun All</name>
                <url>https://maven.aliyun.com/repository/public</url>
              </mirror>
            </mirrors>
          </settings>
          XML

      - name: Preinstall SDL libs (macOS)
        if: runner.os == 'macOS'
        run: |
          mvn -s "$HOME/.m2/settings.xml" $MAVEN_FLAGS install:install-file \
            -Dfile=vendor/sdl-libs-2.0.9-mac.jar \
            -DgroupId=org.datavyu \
            -DartifactId=sdl-libs \
            -Dversion=2.0.9 \
            -Dpackaging=jar \
            -Dclassifier=mac

      - name: Show effective POM
        run: mvn -s "$HOME/.m2/settings.xml" $MAVEN_FLAGS -U -DforceStdout help:effective-pom

      - name: Show dependency tree
        run: mvn -s "$HOME/.m2/settings.xml" $MAVEN_FLAGS -U dependency:tree -DoutputType=text

      - name: Build native installers
        run: mvn -s "$HOME/.m2/settings.xml" $MAVEN_FLAGS -Dmaven.test.skip=true -U clean jfx:native

      - uses: actions/upload-artifact@v4
        with:
          name: datavyu-${{ runner.os }}
          path: |
            target/jfx/native/**/*
            target/*.jar
