name: Build Datavyu

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, windows-latest]

    env:
      MAVEN_FLAGS: "-B -ntp"
      MAVEN_OPTS: >-
        -Xmx2g
        -Dfile.encoding=UTF-8
        -Dswing.aatext=true
        -Dawt.useSystemAAFontSettings=lcd
        -Dorg.apache.maven.wagon.httpconnectionManager.ttl=120000
        -Dorg.apache.maven.wagon.http.retryHandler.count=2
      APP_MAIN: "org.datavyu.Datavyu"
      APP_NAME: "Datavyu"
      APP_VENDOR: "Datavyu"

    steps:
      - uses: actions/checkout@v4

      # JDK8 + JavaFX（必须带 FX；Liberica 自带 javapackager/ant-javafx.jar）
      - name: Set up JDK 8 (Liberica with JavaFX)
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: '8'
          java-package: jdk+fx
          cache: maven

      - name: Verify JavaFX packager tools
        shell: bash
        run: |
          set -e
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          test -x "$JAVA_HOME/bin/javapackager" && echo "✔ javapackager OK" || (echo "✘ javapackager MISSING" && exit 1)
          test -f "$JAVA_HOME/lib/ant-javafx.jar" && echo "✔ ant-javafx.jar OK" || (echo "✘ ant-javafx.jar MISSING" && exit 1)

      # Windows 打原生安装包需要工具
      - name: Install Windows packaging tools (InnoSetup + WiX)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install -y innosetup wixtoolset

      # Maven 源加速
      - name: Set up Maven mirrors
        shell: bash
        run: |
          mkdir -p "$HOME/.m2"
          cat > "$HOME/.m2/settings.xml" <<'XML'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <mirrors>
              <mirror>
                <id>aliyun-central</id>
                <mirrorOf>central,!apache-central</mirrorOf>
                <url>https://maven.aliyun.com/repository/central</url>
              </mirror>
              <mirror>
                <id>fast-fail-others</id>
                <mirrorOf>rubygems-releases,bintray-datavyu-datavyu</mirrorOf>
                <url>https://repo.maven.apache.org/maven2</url>
              </mirror>
            </mirrors>
            <profiles>
              <profile>
                <id>extra-repos</id>
                <activation><activeByDefault>true</activeByDefault></activation>
                <repositories>
                  <repository>
                    <id>apache-central</id>
                    <url>https://repo.maven.apache.org/maven2</url>
                    <releases><enabled>true</enabled><updatePolicy>never</updatePolicy></releases>
                    <snapshots><enabled>false</enabled></snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
          </settings>
          XML

      # （可选）预装 vendor/* 私有 JAR（按平台 classifier）
      - name: Preinstall vendor jars (optional)
        shell: bash
        run: |
          set -e
          CLASSIFIER=""
          if [ "$RUNNER_OS" = "macOS" ]; then CLASSIFIER="mac"; fi
          if [ "$RUNNER_OS" = "Windows" ]; then CLASSIFIER="win"; fi
          for f in vendor/sdl-libs-2.0.9-${CLASSIFIER}.jar \
                   vendor/ffmpeg-libs-4.1.1-${CLASSIFIER}.jar \
                   vendor/ffmpeg-plugin-0.24-${CLASSIFIER}.jar ; do
            if [ -f "$f" ]; then
              AID=$(basename "$f" | sed -E 's/-[0-9].*//')
              VER=$(basename "$f" | sed -E 's/.*-([0-9][^.]*(\.[0-9]+)*)[^/]*\.jar/\1/')
              mvn -s "$HOME/.m2/settings.xml" -B install:install-file \
                -Dfile="$f" -DgroupId=org.datavyu -DartifactId="$AID" \
                -Dversion="$VER" -Dpackaging=jar -Dclassifier="${CLASSIFIER}"
            fi
          done
          if [ "$RUNNER_OS" = "macOS" ]; then
            if [ -f vendor/quaqua-osx64-7.0.1.jar ]; then
              mvn -s "$HOME/.m2/settings.xml" -B install:install-file \
                -Dfile=vendor/quaqua-osx64-7.0.1.jar \
                -DgroupId=org.datavyu -DartifactId=quaqua-osx64 \
                -Dversion=7.0.1 -Dpackaging=jar
            fi
            if [ -f vendor/quaqua-filechooser-only-7.0.1.jar ]; then
              mvn -s "$HOME/.m2/settings.xml" -B install:install-file \
                -Dfile=vendor/quaqua-filechooser-only-7.0.1.jar \
                -DgroupId=org.datavyu -DartifactId=quaqua-filechooser-only \
                -Dversion=7.0.1 -Dpackaging=jar
            fi
          fi

      # —— 测试阶段 ————————————————————————————————————————————

      # 准备测试数据：把 src/test/resources/IO 拷到项目根，满足相对路径 IO/...
      - name: Prepare test data (copy IO to project root)
        shell: bash
        run: |
          set -e
          if [ -d src/test/resources/IO ]; then
            rm -rf IO
            cp -a src/test/resources/IO .
            echo "Copied src/test/resources/IO -> ./IO"
            ls -l IO | head -n 50
          else
            echo "No src/test/resources/IO found"
          fi

      # 运行测试（失败时上传报告并终止）
      - name: Run tests
        shell: bash
        run: |
          set -e
          mvn -s "$HOME/.m2/settings.xml" $MAVEN_FLAGS -U test

      - name: Upload surefire reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ runner.os }}
          path: target/surefire-reports/**
          if-no-files-found: ignore

      # —— 打包阶段（跳过测试，避免 jfx:native 再次触发测试）———————————————

      # 先产出 appdir（供 bundler 使用）
      - name: Build appdir (no tests)
        run: mvn -s "$HOME/.m2/settings.xml" $MAVEN_FLAGS -DskipTests -Dmaven.test.skip=true -Dtest.skip=true -U clean jfx:jar

      # macOS：明确传入 runtime，生成 DMG/PKG；无产物则失败
      - name: Build DMG/PKG (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          set -e
          if [ -d "$JAVA_HOME/jre" ]; then
            RUNTIME_DIR="$JAVA_HOME/jre"
          else
            RUNTIME_DIR="$JAVA_HOME"
          fi
          echo "Using runtime: $RUNTIME_DIR"

          mvn -s "$HOME/.m2/settings.xml" $MAVEN_FLAGS \
            -DskipTests -Dmaven.test.skip=true -Dtest.skip=true \
            -Djavafx.native=true \
            -Djavafx.native.bundlers="DMG Installer,PKG Installer" \
            -Djavafx.native.bundlerArgs="runtime,${RUNTIME_DIR},mac.sign,false,mac.CFBundleIdentifier,org.datavyu" \
            -Djavafx.mainClass="${APP_MAIN}" \
            -Djavafx.appName="${APP_NAME}" \
            -Djavafx.vendor="${APP_VENDOR}" \
            -Djavafx.verbose=true \
            jfx:native

          echo "== produced DMG/PKG =="
          FOUND=$(find target -maxdepth 6 -type f \( -name "*.dmg" -o -name "*.pkg" \) | wc -l | tr -d ' ')
          if [ "$FOUND" = "0" ]; then
            echo "✘ No DMG/PKG produced. Failing the build."
            exit 1
          fi
          find target -maxdepth 6 -type f \( -name "*.dmg" -o -name "*.pkg" \) -print

      # Windows：EXE/MSI；无产物则失败
      - name: Build EXE/MSI (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          mvn $env:MAVEN_FLAGS `
            -DskipTests -Dmaven.test.skip=true -Dtest.skip=true `
            -Djavafx.native=true `
            -Djavafx.native.bundlers="EXE Installer,MSI Installer" `
            -Djavafx.mainClass="$env:APP_MAIN" `
            -Djavafx.appName="$env:APP_NAME" `
            -Djavafx.vendor="$env:APP_VENDOR" `
            -Djavafx.verbose=true `
            jfx:native

          Write-Host "== produced EXE/MSI =="
          $files = Get-ChildItem -Recurse -Path target -Include *.exe,*.msi -ErrorAction SilentlyContinue
          if (-not $files) {
            Write-Error "No EXE/MSI produced. Failing the build."
          } else {
            $files | ForEach-Object { $_.FullName }
          }

      # 列出产物
      - name: Inspect outputs
        if: always()
        shell: bash
        run: |
          echo "== files ==" && find target -maxdepth 6 -type f -print || true
          echo "== app bundles ==" && find target -maxdepth 6 -type d -name "*.app" -print || true

      # 兜底：总是把 appdir 打一个 zip，便于人工排查/手动运行
      - name: Package jfx appdir (always)
        if: always()
        shell: bash
        run: |
          if [ -d target/jfx/app ]; then
            (cd target/jfx/app && zip -r ../../${{ env.APP_NAME }}-${{ runner.os }}-appdir.zip .)
          fi

      # 上传所有产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datavyu-${{ runner.os }}
          path: |
            target/**/*.dmg
            target/**/*.pkg
            target/**/*.msi
            target/**/*.exe
            target/*-appdir.zip
            target/**/*.app.zip
            target/jfx/native/**/*
            target/jfx/app/*-jfx.jar
            target/*-jfx.jar
          if-no-files-found: warn
