name: Build Datavyu (Windows only)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-win:
    runs-on: windows-latest

    env:
      # 不再使用 MAVEN_FLAGS，避免被 PowerShell 误切分
      MAVEN_OPTS: >-
        -Xmx2g
        -Dfile.encoding=UTF-8
        -Dswing.aatext=true
        -Dawt.useSystemAAFontSettings=lcd
        -Dorg.apache.maven.wagon.httpconnectionManager.ttl=120000
        -Dorg.apache.maven.wagon.http.retryHandler.count=2
      APP_MAIN: "org.datavyu.Datavyu"
      APP_NAME: "Datavyu"
      APP_VENDOR: "Datavyu"

    steps:
      - uses: actions/checkout@v4

      # ===== JDK8 + JavaFX =====
      - name: Set up JDK 8 (Liberica with JavaFX)
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: '8'
          java-package: jdk+fx
          cache: maven

      - name: Verify JavaFX packager tools
        shell: pwsh
        run: |
          Write-Host "JAVA_HOME=$env:JAVA_HOME"
          & "$env:JAVA_HOME\bin\java.exe" -version
          if (Test-Path "$env:JAVA_HOME\bin\javapackager.exe") {
            & "$env:JAVA_HOME\bin\javapackager.exe" -version
          } else {
            Write-Warning "javapackager.exe not found (Liberica 8 + FX should include it)."
          }
          if (Test-Path "$env:JAVA_HOME\lib\ant-javafx.jar") {
            Write-Host "ant-javafx.jar OK"
          }

      # ===== Windows 打包工具 =====
      - name: Install Windows packaging tools (InnoSetup + WiX)
        shell: pwsh
        run: |
          choco install -y innosetup wixtoolset

      # ===== Maven mirrors（可按需调整或删除）=====
      - name: Set up Maven mirrors
        shell: pwsh
        run: |
          New-Item -Force -ItemType Directory "$HOME\.m2" | Out-Null
          @"
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <mirrors>
              <mirror>
                <id>aliyun-central</id>
                <mirrorOf>central,!apache-central</mirrorOf>
                <url>https://maven.aliyun.com/repository/central</url>
              </mirror>
              <mirror>
                <id>fast-fail-others</id>
                <mirrorOf>rubygems-releases,bintray-datavyu-datavyu</mirrorOf>
                <url>https://repo.maven.apache.org/maven2</url>
              </mirror>
            </mirrors>
            <profiles>
              <profile>
                <id>extra-repos</id>
                <activation><activeByDefault>true</activeByDefault></activation>
                <repositories>
                  <repository>
                    <id>apache-central</id>
                    <url>https://repo.maven.apache.org/maven2</url>
                    <releases><enabled>true</enabled><updatePolicy>never</updatePolicy></releases>
                    <snapshots><enabled>false</enabled></snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
          </settings>
          "@ | Set-Content -Encoding UTF8 "$HOME\.m2\settings.xml"

      # ===== 预装 vendor JAR（用 bash，避免 pwsh 续行/转义坑）=====
      - name: Preinstall vendor jars (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.m2"
          jars=(
            "vendor/ffmpeg-libs-4.1.1-win.jar"
            "vendor/ffmpeg-plugin-0.24-win.jar"
            "vendor/sdl-libs-2.0.9-win.jar"
          )
          for f in "${jars[@]}"; do
            if [[ -f "$f" ]]; then
              AID=$(basename "$f" | sed -E 's/-[0-9].*//')
              VER=$(basename "$f" | sed -E 's/.*-([0-9][^-.]*([\.][0-9]+)*).*-win\.jar/\1/')
              mvn -s "$HOME/.m2/settings.xml" -B -ntp install:install-file \
                -Dfile="$f" \
                -DgroupId="org.datavyu" \
                -DartifactId="$AID" \
                -Dversion="$VER" \
                -Dpackaging=jar \
                -Dclassifier="win"
            fi
          done
          # 可视化确认坐标
          ls -R "$HOME/.m2/repository/org/datavyu" || true

      # ===== 准备测试资源 =====
      - name: Prepare test resources for file-path based tests
        shell: pwsh
        run: |
          if (Test-Path "IO") { Remove-Item -Recurse -Force "IO" }
          if (Test-Path "src\test\resources\IO") {
            New-Item -ItemType Directory -Force "IO" | Out-Null
            Copy-Item -Recurse "src\test\resources\IO\*" "IO\"
          } else {
            Write-Error "src/test/resources/IO not found"; exit 1
          }

      # ===== 运行测试（尽量运行，不阻断打包）=====
      - name: Run unit tests (best effort)
        shell: pwsh
        continue-on-error: true
        run: |
          $args = @(
            "-s", "$HOME\.m2\settings.xml",
            "-B", "-ntp",
            "-U",
            "test"
          )
          & mvn @args

      - name: Upload surefire reports (on test failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-windows
          path: |
            **/target/surefire-reports/**
            **/target/*.dump*
            **/target/*-jvmRun*.dump*
          if-no-files-found: ignore

      # ===== 先产出 JavaFX appdir（跳过测试）=====
      - name: Build appdir (skip tests)
        shell: pwsh
        run: |
          $args = @(
            "-s", "$HOME\.m2\settings.xml",
            "-B", "-ntp",
            "-U",
            "-DskipTests", "-Dmaven.test.skip=true", "-Dtest.skip=true",
            "clean", "jfx:jar"
          )
          & mvn @args

      # ===== 产出 EXE/MSI =====
      - name: Build EXE/MSI (Windows)
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $args = @(
            "-s", "$HOME\.m2\settings.xml",
            "-B", "-ntp",
            "-U",
            "-DskipTests", "-Dmaven.test.skip=true", "-Dtest.skip=true",
            "-Djfx.native=true",
            '-Djfx.native.bundlers=EXE Installer,MSI Installer',
            "-Djavafx.verbose=true",
            "-Djavafx.mainClass=$env:APP_MAIN",
            "-Djavafx.appName=$env:APP_NAME",
            "-Djavafx.vendor=$env:APP_VENDOR",
            "jfx:native"
          )
          & mvn @args
          Write-Host "== produced EXE/MSI =="
          $files = Get-ChildItem -Recurse -Path target -Include *.exe,*.msi -ErrorAction SilentlyContinue
          if (-not $files) { Write-Error "No EXE/MSI produced. Failing the build." } else { $files | ForEach-Object { $_.FullName } }

      # ===== 打包 appdir 以便调试 =====
      - name: Package jfx appdir (always)
        if: always()
        shell: pwsh
        run: |
          if (Test-Path "target\jfx\app") {
            $zip = "target\${env:APP_NAME}-Windows-appdir.zip"
            if (Test-Path $zip) { Remove-Item $zip -Force }
            Compress-Archive -Path "target\jfx\app\*" -DestinationPath $zip
          }

      # ===== 上传产物 =====
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datavyu-windows
          path: |
            target/**/*.msi
            target/**/*.exe
            target/*-Windows-appdir.zip
            target/jfx/native/**/*
            target/jfx/app/*-jfx.jar
            target/*-jfx.jar
          if-no-files-found: warn
