name: Build Datavyu

on:
  push:
    branches: [ main, master ]  # 视你的默认分支调整
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]  # 先只跑 macOS，Windows 暂时注释以减少变量

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '8'

      - name: Preinstall SDL libs (macOS)
        if: runner.os == 'macOS'
        run: |
          mvn install:install-file \
            -Dfile=vendor/sdl-libs-2.0.9-mac.jar \
            -DgroupId=org.datavyu \
            -DartifactId=sdl-libs \
            -Dversion=2.0.9 \
            -Dpackaging=jar \
            -Dclassifier=mac

      - name: Show effective POM
        run: mvn -B -U -DforceStdout help:effective-pom

      - name: Show dependency tree
        run: mvn -B -U dependency:tree -DoutputType=text

      - name: Set up Maven mirror for faster downloads
        run: |
          mkdir -p ~/.m2
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                    https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <mirrors>
              <mirror>
                <id>aliyunmaven</id>
                <mirrorOf>central</mirrorOf>
                <name>Aliyun Maven</name>
                <url>https://maven.aliyun.com/repository/central</url>
              </mirror>
            </mirrors>
          </settings>' > ~/.m2/settings.xml

      - name: Build native installers
        run: mvn -Dmaven.test.skip=true -U clean jfx:native
        env:
          MAVEN_OPTS: "-Xmx1g -Dfile.encoding=UTF-8 -Dswing.aatext=true -Dawt.useSystemAAFontSettings=lcd"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datavyu-${{ runner.os }}
          path: |
            target/jfx/native/**/*
            target/*.jar

